package com.example.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

data class Strings(
    // App & Common
    val appName: String,
    val driver: String,
    val cancel: String,
    val save: String,
    val saveChanges: String,
    val confirm: String,
    val close: String,
    val ok: String,
    val error: String,
    val retry: String,
    val simulated: String,
    val connected: String,
    val disconnected: String,
    val offline: String,
    val yes: String,
    val no: String,
    val notSet: String,

    // Navigation
    val navHome: String,
    val navHistory: String,
    val navInsights: String,
    val navStatus: String,
    val navSettings: String,
    val navOrientation3D: String,

    // Top Bars
    val dashboardTitle: String,
    val dashboardSubtitle: String,
    val historyTitle: String,
    val historySubtitle: String,
    val insightsTitle: String,
    val insightsSubtitle: String,
    val statusTitle: String,
    val statusSubtitle: String,
    val settingsTitle: String,
    val settingsSubtitle: String,
    val orientation3DTitle: String,
    val orientation3DSubtitle: String,

    // Insights Screen
    val requestsThisWeek: String,
    val requestBreakdown: String,
    val totalRequestsThisWeek: String,
    val totalRequestsAllTime: String,
    val busiestHourTitle: String,
    val busiestHourSubtitle: String,
    val averageResponseTimeTitle: String,
    val averageResponseTimeSubtitle: String,
    val callsLabel: String,
    val todayBadge: String,
    val vsLastWeek: String,
    val noRequestsLogged: String,
    val generateSampleData: String,
    val sampleDataGenerated: String,
    val coverageTitle: String,
    val coverageSubtitle: String,
    val avgResponseCardTitle: String,
    val peakHourCardTitle: String,
    val requestsTodayTitle: String,
    val performanceTitle: String,
    val responseRateTitle: String,
    val totalCallsTitle: String,
    val completionRateTitle: String,
    val weeklySummaryTitle: String,
    val weeklySummarySubtitle: String,
    val swipeHint: String,

    // Home / Dashboard
    val driverAvailability: String,
    val activeReady: String,
    val offDutyBusy: String,
    val active: String,
    val offDuty: String,
    val hardwareBattery: String,
    val standButton: String,
    val checkBattery: String,
    val checking: String,
    val testAlert: String,
    val sendTestAlert: String,
    val pendingServiceCalls: String,
    val noPendingCalls: String,
    val waitingForPassengers: String,
    val incomingServiceCall: String,
    val location: String,
    val autoStandModule: String,
    val actionComing: String,
    val actionBusy: String,
    val todaySummary: String,
    val totalCalls: String,
    val acceptedCalls: String,
    val pendingCalls: String,
    val cancelledCalls: String,
    val acceptanceRate: String,
    val lowBatteryWarning: String,
    val serviceCall: String,

    // History
    val callHistoryTitle: String,
    val clearAllLogs: String,
    val noPastCalls: String,
    val clearHistoryConfirm: String,
    val clear: String,
    val requestId: String,
    val response: String,
    val unanswered: String,

    // Device Status
    val hardwareModuleStatus: String,
    val pingHardware: String,
    val pinging: String,
    val batteryHealth: String,
    val batteryLevel: String,
    val voltage: String,
    val chargingStatus: String,
    val charging: String,
    val notCharging: String,
    val lastPingStatus: String,
    val normal: String,
    val critical: String,
    val ipAddress: String,

    // Settings
    val languageSection: String,
    val languageSubtitle: String,
    val english: String,
    val malayalam: String,
    val primaryDriverNumber: String,
    val primaryDriverSubtitle: String,
    val backupDriverNumber: String,
    val backupDriverSubtitle: String,
    val changePrimaryNumber: String,
    val changeBackupNumber: String,
    val primaryNumberDialogTitle: String,
    val backupNumberDialogTitle: String,
    val devicePasswordLabel: String,
    val alertSoundTitle: String,
    val requestTimeoutTitle: String,
    val pushTestTitle: String,
    val pushTestSubtitle: String,
    val sendTestPush: String,
    val aboutTitle: String,
    val aboutDescription: String,
    val rePairTitle: String,
    val rePairSubtitle: String,
    val backupPhoneUpdatedSuccess: String,
    val primaryPhoneUpdatedSuccess: String,
    val passwordIncorrect: String,

    // Notifications & Escalation
    val notifReminderTitle: String,
    val notifReminderText: String,
    val notifBackupAlertTitle: String,
    val notifBackupAlertText: String,
    val notifRepliedComing: String,
    val notifRepliedBusy: String,
    val notifResponseSent: String,

    // Pairing
    val pairingTitle: String,
    val pairingReconfigureTitle: String,
    val pairingSubtitle: String,
    val mdnsDiscovery: String,
    val scanningForButton: String,
    val buttonFound: String,
    val discoveryTimedOut: String,
    val primaryPhoneLabel: String,
    val backupPhoneLabel: String,
    val connectDevice: String,
    val connectingDevice: String,
    val manualIpFallback: String,

    // WiFi Configuration
    val wifiSetupTitle: String,
    val wifiSetupSubtitle: String,
    val connectViaUsb: String,
    val connectViaAp: String,
    val usbOtgRecommended: String,
    val localApFallback: String,
    val wifiSsidLabel: String,
    val wifiPasswordLabel: String,
    val sendWifiConfig: String,
    val configuringWifi: String,
    val noUsbDeviceDetected: String,
    val usbDeviceDetected: String,
    val permissionRequired: String,
    val grantUsbPermission: String,
    val noResponseTimeout: String,
    val newDeviceIp: String,
    val useIpInApp: String,
    val serialLogTitle: String,
    val wifiConfigSuccess: String,
    val primaryWifiTitle: String,
    val backupWifiTitle: String,
    val backupWifiSubtitle: String,
    val sendBackupWifiConfig: String,
    val configuringBackupWifi: String,
    val devicePasswordWifiNote: String,

    // Backup Viewer & Roles
    val setupRoleTitle: String,
    val setupRoleSubtitle: String,
    val setupRoleOwner: String,
    val setupRoleViewer: String,
    val backupViewerCardTitle: String,
    val backupViewerCardSubtitle: String,
    val deviceOwnerPasswordLabel: String,
    val deviceOwnerPasswordHelper: String,
    val viewerPhoneLabel: String,
    val linkAsBackupViewer: String,
    val linkingBackupViewer: String,
    val backupViewerLinkedSuccess: String,
    val backupViewerRoleBadge: String,
    val backupViewerSettingsTitle: String,
    val safetyTiltAlertsTitle: String,
    val safetyTiltAlertsSubtitle: String,
    val regularRideAlertsTitle: String,
    val regularRideAlertsSubtitle: String,
    val regularRideAlertsComingSoon: String,
    val backupViewersSectionTitle: String,
    val backupViewersSectionSubtitle: String,
    val revokeAllViewersButton: String,
    val revokeAllViewersDialogTitle: String,
    val revokeAllViewersDialogText: String,
    val revokeAllViewersSuccess: String,
    val revokingViewers: String,
    val unlinkDevice: String
)

val EnglishStrings = Strings(
    appName = "AutoAlert",
    driver = "Driver",
    cancel = "Cancel",
    save = "Save",
    saveChanges = "Save Changes",
    confirm = "Confirm",
    close = "Close",
    ok = "OK",
    error = "Error",
    retry = "Retry",
    simulated = "Simulated",
    connected = "Connected",
    disconnected = "Disconnected",
    offline = "Offline",
    yes = "Yes",
    no = "No",
    notSet = "Not set",

    navHome = "Home",
    navHistory = "History",
    navInsights = "Insights",
    navStatus = "Status",
    navSettings = "Settings",
    navOrientation3D = "3D Auto",

    dashboardTitle = "AutoAlert Dashboard",
    dashboardSubtitle = "Real-time Kerala Stand Dispatch",
    historyTitle = "Call History",
    historySubtitle = "Dispatched ride logs & driver actions",
    insightsTitle = "AutoAlert Insights",
    insightsSubtitle = "Button press history & stand demand metrics",
    statusTitle = "Device Status",
    statusSubtitle = "ESP8266 IoT button telemetry & network",
    settingsTitle = "App Settings",
    settingsSubtitle = "Configure dispatch, driver & hardware",
    orientation3DTitle = "3D Auto Orientation",
    orientation3DSubtitle = "Real-time MPU6500 Telemetry",

    requestsThisWeek = "Requests This Week",
    requestBreakdown = "Request Breakdown",
    totalRequestsThisWeek = "Total Requests (This Week)",
    totalRequestsAllTime = "Total Requests (All-Time)",
    busiestHourTitle = "Busiest Hour",
    busiestHourSubtitle = "Peak auto stand demand time",
    averageResponseTimeTitle = "Average Response Time",
    averageResponseTimeSubtitle = "From stand button press to driver reply",
    callsLabel = "calls",
    todayBadge = "Today",
    vsLastWeek = "vs last week",
    noRequestsLogged = "No button press requests recorded yet",
    generateSampleData = "Generate Sample Stand Logs",
    sampleDataGenerated = "Sample week data added to history",
    coverageTitle = "Coverage",
    coverageSubtitle = "Most requests from this stand",
    avgResponseCardTitle = "Avg Response",
    peakHourCardTitle = "Peak Hour",
    requestsTodayTitle = "Requests Today",
    performanceTitle = "Performance",
    responseRateTitle = "Response Rate",
    totalCallsTitle = "Total Calls",
    completionRateTitle = "Completion Rate",
    weeklySummaryTitle = "Weekly Summary",
    weeklySummarySubtitle = "View detailed stand analytics & trends",
    swipeHint = "Swipe vertically between Chart & Card Grid",

    driverAvailability = "Driver Availability",
    activeReady = "Active & Ready for calls",
    offDutyBusy = "Off Duty / Busy",
    active = "Active",
    offDuty = "Off Duty",
    hardwareBattery = "Hardware Module Battery",
    standButton = "Stand Button",
    checkBattery = "Check Battery",
    checking = "Checking...",
    testAlert = "Test Alert",
    sendTestAlert = "Send Test Alert",
    pendingServiceCalls = "Pending Service Calls",
    noPendingCalls = "No pending calls. Ready for requests.",
    waitingForPassengers = "Auto stand button is active and monitoring.",
    incomingServiceCall = "Incoming Service Call",
    location = "Location",
    autoStandModule = "Auto Stand Module",
    actionComing = "Coming (5 min)",
    actionBusy = "Busy",
    todaySummary = "Today's Summary",
    totalCalls = "Total Calls",
    acceptedCalls = "Accepted",
    pendingCalls = "Pending",
    cancelledCalls = "Cancelled",
    acceptanceRate = "Acceptance Rate",
    lowBatteryWarning = "Low Battery Warning",
    serviceCall = "Service Call",

    callHistoryTitle = "Call History",
    clearAllLogs = "Clear All Logs",
    noPastCalls = "No past calls logged yet",
    clearHistoryConfirm = "Are you sure you want to clear all call history logs?",
    clear = "Clear",
    requestId = "Request ID",
    response = "Response",
    unanswered = "Unanswered",

    hardwareModuleStatus = "ESP8266 Hardware Module",
    pingHardware = "Ping Hardware Module",
    pinging = "Pinging ESP8266...",
    batteryHealth = "Battery Health",
    batteryLevel = "Battery Level",
    voltage = "Voltage",
    chargingStatus = "Charging Status",
    charging = "Charging (Solar/Mains)",
    notCharging = "Not Charging (On Battery)",
    lastPingStatus = "Last Ping Status",
    normal = "Normal",
    critical = "Critical Low",
    ipAddress = "Resolved IP Address",

    languageSection = "Language (ഭാഷ)",
    languageSubtitle = "Select application display language",
    english = "English",
    malayalam = "മലയാളം (Malayalam)",
    primaryDriverNumber = "Linked Driver Number",
    primaryDriverSubtitle = "Receives primary call notifications via ntfy",
    backupDriverNumber = "Backup Driver Number",
    backupDriverSubtitle = "Receives escalation alert if primary driver does not respond",
    changePrimaryNumber = "Change Driver Number",
    changeBackupNumber = "Change Backup Number",
    primaryNumberDialogTitle = "Update Driver Phone Number",
    backupNumberDialogTitle = "Update Backup Driver Number",
    devicePasswordLabel = "ESP8266 Device Password",
    alertSoundTitle = "Alert Sound",
    requestTimeoutTitle = "Service Request Timeout",
    pushTestTitle = "Push Notification Test",
    pushTestSubtitle = "Verify sound, vibration & action buttons",
    sendTestPush = "Send Test Push Alert",
    aboutTitle = "About AutoAlert Kerala",
    aboutDescription = "Smart auto-rickshaw stand calling module for Kerala. Instant push notifications via ESP8266 hardware button and ntfy.sh messaging.",
    rePairTitle = "Re-pair / Re-initialize Device",
    rePairSubtitle = "Connect to new stand or reset Wi-Fi configuration",
    backupPhoneUpdatedSuccess = "Backup driver number updated successfully on device and app",
    primaryPhoneUpdatedSuccess = "Primary driver number updated successfully",
    passwordIncorrect = "Incorrect password for ESP8266 device",

    notifReminderTitle = "🚨 Reminder: Call Unacknowledged",
    notifReminderText = "Service call at Auto Stand is waiting for driver response!",
    notifBackupAlertTitle = "🚨 Backup Alert: Primary driver unavailable",
    notifBackupAlertText = "Escalated Request: Primary driver unavailable. Passenger waiting at Auto Stand!",
    notifRepliedComing = "You replied: Coming (5 min)",
    notifRepliedBusy = "You replied: Busy",
    notifResponseSent = "Response sent to Auto Stand.",

    pairingTitle = "1-Tap Device Pairing",
    pairingReconfigureTitle = "Device Re-configuration",
    pairingSubtitle = "Auto-discovers your AutoAlert button on local WiFi via mDNS",
    mdnsDiscovery = "mDNS Auto-Discovery",
    scanningForButton = "Scanning for AutoAlert button...",
    buttonFound = "AutoAlert ESP8266 Discovered!",
    discoveryTimedOut = "mDNS Auto-Discovery Timed Out",
    primaryPhoneLabel = "Primary Driver Phone Number",
    backupPhoneLabel = "Backup Driver Phone Number (Escalation)",
    connectDevice = "Connect Device",
    connectingDevice = "Connecting to Device...",
    manualIpFallback = "Manual Numeric IP Fallback",

    wifiSetupTitle = "Hardware Button Wi-Fi Setup",
    wifiSetupSubtitle = "Configure stand Wi-Fi credentials for AutoAlert ESP8266",
    connectViaUsb = "Connect via USB",
    connectViaAp = "Connect via Local AP",
    usbOtgRecommended = "USB-OTG Serial (Primary & Fast)",
    localApFallback = "Local AP (/wifi-config Fallback)",
    wifiSsidLabel = "Wi-Fi Network Name (SSID)",
    wifiPasswordLabel = "Wi-Fi Password",
    sendWifiConfig = "Send Wi-Fi Configuration",
    configuringWifi = "Configuring ESP8266 Wi-Fi...",
    noUsbDeviceDetected = "No USB serial device detected. Please connect your phone to the ESP8266 via a USB-OTG cable.",
    usbDeviceDetected = "USB Device Connected",
    permissionRequired = "USB Permission Required",
    grantUsbPermission = "Grant USB Access",
    noResponseTimeout = "No response from device — check the cable connection",
    newDeviceIp = "Assigned Device IP",
    useIpInApp = "Use This IP for Device",
    serialLogTitle = "ESP8266 Serial Log Terminal",
    wifiConfigSuccess = "Wi-Fi Configured Successfully!",
    primaryWifiTitle = "Auto Stand Wi-Fi (Primary)",
    backupWifiTitle = "Driver's Phone Hotspot (Backup Wi-Fi)",
    backupWifiSubtitle = "Used automatically if the auto stand WiFi goes out of range while on the road.",
    sendBackupWifiConfig = "Send Backup Wi-Fi Configuration",
    configuringBackupWifi = "Configuring ESP8266 Backup Wi-Fi...",
    devicePasswordWifiNote = "Required only if device is already paired. Leave blank for fresh setup.",

    setupRoleTitle = "Select Setup Role",
    setupRoleSubtitle = "Choose how you want to connect to the AutoAlert device",
    setupRoleOwner = "Set up my own device",
    setupRoleViewer = "Add myself as a backup viewer for someone else's device",
    backupViewerCardTitle = "Backup Safety Viewer Setup",
    backupViewerCardSubtitle = "Receive emergency safety & vehicle tilt alerts. You will not receive passenger ride calls.",
    deviceOwnerPasswordLabel = "Device Master Password",
    deviceOwnerPasswordHelper = "Ask the device owner to type this in for you. This password will never be saved on your phone.",
    viewerPhoneLabel = "Your Phone Number (Viewer)",
    linkAsBackupViewer = "Link as Backup Viewer",
    linkingBackupViewer = "Linking Backup Viewer...",
    backupViewerLinkedSuccess = "Linked as backup viewer! You will receive safety & tilt alerts.",
    backupViewerRoleBadge = "Backup Viewer Mode",
    backupViewerSettingsTitle = "Backup Safety Viewer Settings",
    safetyTiltAlertsTitle = "Safety & Tilt Alerts",
    safetyTiltAlertsSubtitle = "Receive notifications if vehicle tilt or rollover is detected",
    regularRideAlertsTitle = "Regular Ride Dispatch Notifications",
    regularRideAlertsSubtitle = "Passenger ride requests and button calls from the auto stand",
    regularRideAlertsComingSoon = "Coming soon: Upgrading backup viewer to full ride dispatch is not yet supported by device firmware.",
    backupViewersSectionTitle = "Backup Viewers Access",
    backupViewersSectionSubtitle = "Family members linked to receive safety & tilt alerts",
    revokeAllViewersButton = "Revoke All Backup Viewer Access",
    revokeAllViewersDialogTitle = "Revoke All Backup Viewers?",
    revokeAllViewersDialogText = "Enter device master password to revoke access. This will remove ALL backup viewers — anyone who should keep access will need to be re-linked.",
    revokeAllViewersSuccess = "All backup viewer access revoked successfully",
    revokingViewers = "Revoking access...",
    unlinkDevice = "Unlink from Device"
)

val MalayalamStrings = Strings(
    appName = "ഓട്ടോ അലേർട്ട്",
    driver = "ഡ്രൈവർ",
    cancel = "റദ്ദാക്കുക",
    save = "സംരക്ഷിക്കുക",
    saveChanges = "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
    confirm = "സ്ഥിരീകരിക്കുക",
    close = "അടയ്ക്കുക",
    ok = "ശരി",
    error = "തകരാറ്",
    retry = "വീണ്ടും ശ്രമിക്കുക",
    simulated = "സിമുലേറ്റഡ്",
    connected = "കണക്ട് ചെയ്തു",
    disconnected = "കണക്ഷൻ ഇല്ല",
    offline = "ഓഫ്‌ലൈൻ",
    yes = "ഉണ്ട്",
    no = "ഇല്ല",
    notSet = "നൽകിയിട്ടില്ല",

    navHome = "ഹോം",
    navHistory = "ഹിസ്റ്ററി",
    navInsights = "ഇൻസൈറ്റ്സ്",
    navStatus = "സ്റ്റാറ്റസ്",
    navSettings = "ക്രമീകരണങ്ങൾ",
    navOrientation3D = "3D കാഴ്ച",

    dashboardTitle = "ഓട്ടോ അലേർട്ട് ഡാഷ്‌ബോർഡ്",
    dashboardSubtitle = "കേരള ഓട്ടോ സ്റ്റാൻഡ് ഡിസ്പാച്ച് സിസ്റ്റം",
    historyTitle = "കോൾ വിവരങ്ങൾ",
    historySubtitle = "മുൻകാല റൈഡ് കോളുകളും ഡ്രൈവർ മറുപടികളും",
    insightsTitle = "ഓട്ടോ അലേർട്ട് ഇൻസൈറ്റ്സ്",
    insightsSubtitle = "സ്റ്റാൻഡ് ബട്ടൺ കോൾ കണക്കുകളും വിവരങ്ങളും",
    statusTitle = "ഡിവൈസ് നില",
    statusSubtitle = "ESP8266 ഐഒടി ബട്ടൺ വിവരങ്ങളും കണക്ഷനും",
    settingsTitle = "ആപ്പ് ക്രമീകരണങ്ങൾ",
    settingsSubtitle = "ഡിസ്പാച്ച്, ഡ്രൈവർ, ഹാർഡ്‌വെയർ മാറ്റങ്ങൾ",
    orientation3DTitle = "3D വാഹനാവസ്ഥ",
    orientation3DSubtitle = "തത്സമയ MPU6500 ടെലിമെട്രി",

    requestsThisWeek = "ഈ ആഴ്ചയിലെ കോളുകൾ",
    requestBreakdown = "കോൾ വിശകലനം",
    totalRequestsThisWeek = "ആകെ കോളുകൾ (ഈ ആഴ്ച)",
    totalRequestsAllTime = "ആകെ കോളുകൾ (മുഴുവൻ)",
    busiestHourTitle = "ഏറ്റവും തിരക്കുള്ള സമയം",
    busiestHourSubtitle = "സ്റ്റാൻഡിൽ ഏറ്റവും കൂടുതൽ കോളുകൾ വന്ന സമയം",
    averageResponseTimeTitle = "ശരാശരി മറുപടി സമയം",
    averageResponseTimeSubtitle = "ബട്ടൺ അമർത്തിയ ശേഷം ഡ്രൈവർ മറുപടി നൽകാൻ എടുത്ത സമയം",
    callsLabel = "കോളുകൾ",
    todayBadge = "ഇന്ന്",
    vsLastWeek = "കഴിഞ്ഞ ആഴ്ചയെ അപേക്ഷിച്ച്",
    noRequestsLogged = "ബട്ടൺ കോൾ വിവരങ്ങളൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല",
    generateSampleData = "ഡെമോ വിവരങ്ങൾ ചേർക്കുക",
    sampleDataGenerated = "ഡെമോ വിവരങ്ങൾ രേഖപ്പെടുത്തി",
    coverageTitle = "കവറേജ്",
    coverageSubtitle = "ഈ സ്റ്റാൻഡിൽ നിന്നുള്ള കോളുകൾ",
    avgResponseCardTitle = "ശരാശരി മറുപടി",
    peakHourCardTitle = "പീക്ക് സമയം",
    requestsTodayTitle = "ഇന്നത്തെ കോളുകൾ",
    performanceTitle = "പെർഫോമൻസ്",
    responseRateTitle = "മറുപടി നിരക്ക്",
    totalCallsTitle = "ആകെ കോളുകൾ",
    completionRateTitle = "പൂർത്തീകരണ നിരക്ക്",
    weeklySummaryTitle = "പ്രതിവാര സംഗ്രഹം",
    weeklySummarySubtitle = "സ്റ്റാൻഡ് വിശദാംശങ്ങളും ട്രെൻഡുകളും കാണുക",
    swipeHint = "ചാർട്ടിനും കാർഡുകൾക്കും ഇടയിൽ ലംബമായി സ്വൈപ്പ് ചെയ്യുക",

    driverAvailability = "ഡ്രൈവർ ലഭ്യത",
    activeReady = "സജീവം • കോളുകൾക്ക് തയ്യാറാണ്",
    offDutyBusy = "ഡ്യൂട്ടിയിൽ ഇല്ല / തിരക്കിലാണ്",
    active = "സജീവം",
    offDuty = "ഡ്യൂട്ടിയിൽ ഇല്ല",
    hardwareBattery = "ഹാർഡ്‌വെയർ ബാറ്ററി നില",
    standButton = "സ്റ്റാൻഡ് ബട്ടൺ",
    checkBattery = "ബാറ്ററി പരിശോധിക്കുക",
    checking = "പരിശോധിക്കുന്നു...",
    testAlert = "ടെസ്റ്റ് അലേർട്ട്",
    sendTestAlert = "ടെസ്റ്റ് കോൾ അയക്കുക",
    pendingServiceCalls = "തീരുമാനമാകാത്ത കോളുകൾ",
    noPendingCalls = "തീരുമാനമാകാത്ത കോളുകൾ ലഭ്യമല്ല.",
    waitingForPassengers = "ഓട്ടോ സ്റ്റാൻഡ് ബട്ടൺ സജീവമാണ്, കോളുകൾക്കായി കാത്തിരിക്കുന്നു.",
    incomingServiceCall = "യാത്രക്കാരന്റെ കോൾ എത്തിയിട്ടുണ്ട്",
    location = "സ്ഥലം",
    autoStandModule = "ഓട്ടോ സ്റ്റാൻഡ് മൊഡ്യൂൾ",
    actionComing = "വരുന്നു (5 മിനിറ്റ്)",
    actionBusy = "തിരക്കിലാണ്",
    todaySummary = "ഇന്നത്തെ വിവരങ്ങൾ",
    totalCalls = "ആകെ കോളുകൾ",
    acceptedCalls = "സ്വീകരിച്ചത്",
    pendingCalls = "പെൻഡിംഗ്",
    cancelledCalls = "റദ്ദാക്കിയത്",
    acceptanceRate = "സ്വീകരണ നിരക്ക്",
    lowBatteryWarning = "ലോ ബാറ്ററി മുന്നറിയിപ്പ്",
    serviceCall = "യാത്രാ കോൾ",

    callHistoryTitle = "കോൾ വിവരങ്ങൾ",
    clearAllLogs = "വിവരങ്ങൾ മായ്ക്കുക",
    noPastCalls = "കോളുകളൊന്നും ഇതുവരെ രേഖപ്പെടുത്തിയിട്ടില്ല",
    clearHistoryConfirm = "എല്ലാ കോൾ വിവരങ്ങളും മായ്ക്കണമെന്ന് ഉറപ്പാണോ?",
    clear = "മായ്ക്കുക",
    requestId = "റിക്വസ്റ്റ് ഐഡി",
    response = "മറുപടി",
    unanswered = "മറുപടി നൽകിയില്ല",

    hardwareModuleStatus = "ESP8266 ഹാർഡ്‌വെയർ മൊഡ്യൂൾ",
    pingHardware = "കണക്ഷൻ പരിശോധിക്കുക",
    pinging = "ESP8266 പരിശോധിക്കുന്നു...",
    batteryHealth = "ബാറ്ററി നില",
    batteryLevel = "ബാറ്ററി ലെവൽ",
    voltage = "വോൾട്ടേജ്",
    chargingStatus = "ചാർജ്ജിംഗ് നില",
    charging = "ചാർജ്ജ് ചെയ്യുന്നു (സോളാർ / പവർ)",
    notCharging = "ചാർജ്ജ് ചെയ്യുന്നില്ല (ബാറ്ററിയിൽ)",
    lastPingStatus = "അവസാന പരിശോധന",
    normal = "സാധാരണം",
    critical = "വളരെ കുറവ്",
    ipAddress = "ഐപി വിലാസം",

    languageSection = "ഭാഷ (Language)",
    languageSubtitle = "ആപ്ലിക്കേഷൻ ഭാഷ തിരഞ്ഞെടുക്കുക",
    english = "English",
    malayalam = "മലയാളം",
    primaryDriverNumber = "രജിസ്റ്റർ ചെയ്ത ഡ്രൈവർ നമ്പർ",
    primaryDriverSubtitle = "ntfy വഴി പ്രാഥമിക കോൾ നോട്ടിഫിക്കേഷനുകൾ ലഭിക്കും",
    backupDriverNumber = "ബാക്കപ്പ് ഡ്രൈവർ നമ്പർ",
    backupDriverSubtitle = "പ്രാഥമിക ഡ്രൈവർ മറുപടി നൽകിയില്ലെങ്കിൽ ബാക്കപ്പ് ഡ്രൈവർക്ക് അലേർട്ട് എത്തും",
    changePrimaryNumber = "ഡ്രൈവർ നമ്പർ മാറ്റുക",
    changeBackupNumber = "ബാക്കപ്പ് നമ്പർ മാറ്റുക",
    primaryNumberDialogTitle = "ഡ്രൈവർ ഫോൺ നമ്പർ മാറ്റുക",
    backupNumberDialogTitle = "ബാക്കപ്പ് ഡ്രൈവർ നമ്പർ മാറ്റുക",
    devicePasswordLabel = "ESP8266 ഡിവൈസ് പാസ്‌വേഡ്",
    alertSoundTitle = "അലേർട്ട് ശബ്ദം",
    requestTimeoutTitle = "കോൾ കാലാവധി (ടൈംഔട്ട്)",
    pushTestTitle = "നോട്ടിഫിക്കേഷൻ പരിശോധന",
    pushTestSubtitle = "ശബ്ദം, വൈബ്രേഷൻ, ബട്ടണുകൾ പരിശോധിക്കുക",
    sendTestPush = "ടെസ്റ്റ് നോട്ടിഫിക്കേഷൻ അയക്കുക",
    aboutTitle = "ഓട്ടോ അലേർട്ട് കേരളയെക്കുറിച്ച്",
    aboutDescription = "കേരളത്തിലെ ഓട്ടോ സ്റ്റാൻഡുകൾക്കായുള്ള സ്മാർട്ട് കോളിംഗ് സിസ്റ്റം. ESP8266 ബട്ടണും ntfy.sh വഴിയുമുള്ള അതിവേഗ അറിയിപ്പുകൾ.",
    rePairTitle = "ഡിവൈസ് റീ-പെയർ ചെയ്യുക",
    rePairSubtitle = "പുതിയ സ്റ്റാൻഡുമായി ബന്ധിപ്പിക്കുകയോ വൈഫൈ മാറ്റുകയോ ചെയ്യുക",
    backupPhoneUpdatedSuccess = "ബാക്കപ്പ് ഡ്രൈവർ നമ്പർ വിജയകരമായി മാറ്റി",
    primaryPhoneUpdatedSuccess = "ഡ്രൈവർ ഫോൺ നമ്പർ വിജയകരമായി മാറ്റി",
    passwordIncorrect = "ESP8266 ഡിവൈസ് പാസ്‌വേഡ് തെറ്റാണ്",

    notifReminderTitle = "🚨 ഓർമ്മപ്പെടുത്തൽ: പ്രതികരിക്കാത്ത കോൾ",
    notifReminderText = "ഓട്ടോ സ്റ്റാൻഡിലെ കോളിന് ഡ്രൈവറുടെ മറുപടിക്കായി കാത്തിരിക്കുന്നു!",
    notifBackupAlertTitle = "🚨 ബാക്കപ്പ് അലേർട്ട്: പ്രാഥമിക ഡ്രൈവർ ലഭ്യമല്ല",
    notifBackupAlertText = "എസ്കലേറ്റഡ് കോൾ: പ്രാഥമിക ഡ്രൈവർ ലഭ്യമല്ല. ഓട്ടോ സ്റ്റാൻഡിൽ യാത്രക്കാരൻ കാത്തിരിക്കുന്നു!",
    notifRepliedComing = "നിങ്ങൾ മറുപടി നൽകി: വരുന്നു (5 മിനിറ്റ്)",
    notifRepliedBusy = "നിങ്ങൾ മറുപടി നൽകി: തിരക്കിലാണ്",
    notifResponseSent = "മറുപടി ഓട്ടോ സ്റ്റാൻഡിലേക്ക് അയച്ചു.",

    pairingTitle = "ഡിവൈസ് പെയറിംഗ്",
    pairingReconfigureTitle = "ഡിവൈസ് റീ-കോൺഫിഗറേഷൻ",
    pairingSubtitle = "ലോക്കൽ വൈഫൈ വഴി mDNS ഉപയോഗിച്ച് ഓട്ടോ അലേർട്ട് ബട്ടൺ കണ്ടെത്തുന്നു",
    mdnsDiscovery = "mDNS ഓട്ടോ ഡിസ്കവറി",
    scanningForButton = "ഓട്ടോ അലേർട്ട് ബട്ടൺ തിരയുന്നു...",
    buttonFound = "ഓട്ടോ അലേർട്ട് ESP8266 കണ്ടെത്തി!",
    discoveryTimedOut = "ഓട്ടോ ഡിസ്കവറി സമയം കഴിഞ്ഞു",
    primaryPhoneLabel = "പ്രാഥമിക ഡ്രൈവർ ഫോൺ നമ്പർ",
    backupPhoneLabel = "ബാക്കപ്പ് ഡ്രൈവർ ഫോൺ നമ്പർ (എസ്കലേഷൻ)",
    connectDevice = "ഡിവൈസ് കണക്ട് ചെയ്യുക",
    connectingDevice = "ഡിവൈസിലേക്ക് കണക്ട് ചെയ്യുന്നു...",
    manualIpFallback = "മാനുവൽ ഐപി നൽകുക",

    wifiSetupTitle = "ഹാർഡ്‌വെയർ ബട്ടൺ വൈഫൈ ക്രമീകരണം",
    wifiSetupSubtitle = "ഓട്ടോഅലർട്ട് ESP8266-ൽ വൈഫൈ ക്രമീകരിക്കുക",
    connectViaUsb = "USB വഴി കണക്റ്റുചെയ്യുക",
    connectViaAp = "ലോക്കൽ AP വഴി കണക്റ്റുചെയ്യുക",
    usbOtgRecommended = "USB-OTG സീരിയൽ (കൂടുതൽ വിശ്വസനീയം)",
    localApFallback = "ലോക്കൽ AP (/wifi-config ഫാൾബാക്ക്)",
    wifiSsidLabel = "വൈഫൈ നെറ്റ്‌വർക്ക് പേര് (SSID)",
    wifiPasswordLabel = "വൈഫൈ പാസ്‌വേഡ്",
    sendWifiConfig = "വൈഫൈ വിവരങ്ങൾ അയയ്ക്കുക",
    configuringWifi = "വൈഫൈ ക്രമീകരിക്കുന്നു...",
    noUsbDeviceDetected = "USB ഡിവൈസ് കണ്ടെത്തിയില്ല. ഫോൺ ESP8266-ലേക്ക് USB-OTG കേബിൾ വഴി കണക്റ്റുചെയ്യുക.",
    usbDeviceDetected = "USB ഡിവൈസ് കണക്റ്റഡ്",
    permissionRequired = "USB അനുമതി ആവശ്യമാണ്",
    grantUsbPermission = "USB അനുമതി നൽകുക",
    noResponseTimeout = "ഡിവൈസിൽ നിന്ന് മറുപടിയില്ല — കേബിൾ കണക്ഷൻ പരിശോധിക്കുക",
    newDeviceIp = "ലഭിച്ച ഡിവൈസ് IP",
    useIpInApp = "ഈ IP ആപ്പിൽ ഉപയോഗിക്കുക",
    serialLogTitle = "ESP8266 സീരിയൽ ലോഗ്",
    wifiConfigSuccess = "വൈഫൈ വിജയകരമായി ക്രമീകരിച്ചു!",
    primaryWifiTitle = "ഓട്ടോ സ്റ്റാൻഡ് വൈഫൈ (പ്രാഥമികം)",
    backupWifiTitle = "ഡ്രൈവറുടെ ഫോൺ ഹോട്ട്സ്പോട്ട് (ബാക്കപ്പ് വൈഫൈ)",
    backupWifiSubtitle = "വണ്ടി ഓടുമ്പോൾ സ്റ്റാൻഡ് വൈഫൈ പരിധിക്ക് പുറത്തായാൽ ഇത് സ്വയം ഉപയോഗിക്കും.",
    sendBackupWifiConfig = "ബാക്കപ്പ് വൈഫൈ വിവരങ്ങൾ അയയ്ക്കുക",
    configuringBackupWifi = "ബാക്കപ്പ് വൈഫൈ ക്രമീകരിക്കുന്നു...",
    devicePasswordWifiNote = "ഡിവൈസ് മുൻപ് പെയർ ചെയ്തിട്ടുണ്ടെങ്കിൽ മാത്രം ഇത് നൽകുക. ആദ്യ തവണ ശൂന്യമായി ഇടാം.",

    setupRoleTitle = "സെറ്റപ്പ് റോൾ തിരഞ്ഞെടുക്കുക",
    setupRoleSubtitle = "AutoAlert ഡിവൈസുമായി ഈ ആപ്പ് എങ്ങനെ ഉപയോഗിക്കണമെന്ന് തിരഞ്ഞെടുക്കുക",
    setupRoleOwner = "എന്റെ സ്വന്തം ഡിവൈസ് സെറ്റ് ചെയ്യുക",
    setupRoleViewer = "മറ്റൊരാളുടെ ഡിവൈസിനായി ബാക്കപ്പ് വ്യൂവറായി ചേരുക",
    backupViewerCardTitle = "ബാക്കപ്പ് സേഫ്റ്റി വ്യൂവർ സെറ്റപ്പ്",
    backupViewerCardSubtitle = "അടിയന്തര സുരക്ഷാ, ടിൽറ്റ് അലേർട്ടുകൾ മാത്രം ലഭിക്കും. യാത്രാ കോളുകൾ ലഭിക്കില്ല.",
    deviceOwnerPasswordLabel = "ഡിവൈസ് മാസ്റ്റർ പാസ്‌വേഡ്",
    deviceOwnerPasswordHelper = "ഡിവൈസ് ഉടമയോട് ഇത് ടൈപ്പ് ചെയ്യാൻ ആവശ്യപ്പെടുക. ഈ പാസ്‌വേഡ് നിങ്ങളുടെ ഫോണിൽ സൂക്ഷിക്കില്ല.",
    viewerPhoneLabel = "നിങ്ങളുടെ ഫോൺ നമ്പർ (വ്യൂവർ)",
    linkAsBackupViewer = "ബാക്കപ്പ് വ്യൂവറായി ലിങ്ക് ചെയ്യുക",
    linkingBackupViewer = "ബാക്കപ്പ് വ്യൂവർ ലിങ്ക് ചെയ്യുന്നു...",
    backupViewerLinkedSuccess = "ബാക്കപ്പ് വ്യൂവറായി വിജയകരമായി ലിങ്ക് ചെയ്തു!",
    backupViewerRoleBadge = "ബാക്കപ്പ് വ്യൂവർ മോഡ്",
    backupViewerSettingsTitle = "ബാക്കപ്പ് സേഫ്റ്റി വ്യൂവർ ക്രമീകരണങ്ങൾ",
    safetyTiltAlertsTitle = "സുരക്ഷ & ടിൽറ്റ് അലേർട്ടുകൾ",
    safetyTiltAlertsSubtitle = "വാഹനം മറിയുകയോ ചെരിയുകയോ ചെയ്യുമ്പോൾ ഉടനടി അറിയിപ്പ് ലഭിക്കുന്നു",
    regularRideAlertsTitle = "സാധാരണ റൈഡ് ഡിസ്പാച്ച് അറിയിപ്പുകൾ",
    regularRideAlertsSubtitle = "സ്റ്റാൻഡിൽ നിന്നുള്ള യാത്രാ അഭ്യർത്ഥനകൾ",
    regularRideAlertsComingSoon = "ഉടൻ ലഭ്യമാകും: ഫുൾ റൈഡ് ഡിസ്പാച്ച് ആക്സസ് ഫേംവെയറിൽ ഉടൻ പിന്തുണയ്ക്കും.",
    backupViewersSectionTitle = "ബാക്കപ്പ് വ്യൂവർ ആക്സസ്",
    backupViewersSectionSubtitle = "സുരക്ഷാ അലേർട്ടുകൾ ലഭിക്കുന്നതിനായി ലിങ്ക് ചെയ്ത കുടുംബാംഗങ്ങൾ",
    revokeAllViewersButton = "എല്ലാ ബാക്കപ്പ് വ്യൂവർ ആക്സസും റദ്ദാക്കുക",
    revokeAllViewersDialogTitle = "എല്ലാ ബാക്കപ്പ് വ്യൂവർമാരെയും റദ്ദാക്കണോ?",
    revokeAllViewersDialogText = "ഡിവൈസ് മാസ്റ്റർ പാസ്‌വേഡ് നൽകുക. ഇത് എല്ലാ ബാക്കപ്പ് വ്യൂവർമാരെയും നീക്കം ചെയ്യും — തുടരാൻ ആഗ്രഹിക്കുന്നവർ വീണ്ടും ലിങ്ക് ചെയ്യേണ്ടതുണ്ട്.",
    revokeAllViewersSuccess = "എല്ലാ ബാക്കപ്പ് വ്യൂവർ ആക്സസും വിജയകരമായി റദ്ദാക്കി",
    revokingViewers = "റദ്ദാക്കുന്നു...",
    unlinkDevice = "ഡിവൈസ് അൺലിങ്ക് ചെയ്യുക"
)

val LocalStrings = compositionLocalOf { EnglishStrings }
val LocalAppLanguage = compositionLocalOf { "en" }

fun getStrings(language: String): Strings {
    return if (language.lowercase() == "ml") MalayalamStrings else EnglishStrings
}
